// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vetotvet.Data;

namespace Vetotvet.Migrations
{
    [DbContext(typeof(VetotvetDbContext))]
    [Migration("20190713211709_KindAnimalsEdit2")]
    partial class KindAnimalsEdit2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vetotvet.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Breeds");
                });

            modelBuilder.Entity("Vetotvet.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Vetotvet.Models.KindOfAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kind");

                    b.HasKey("Id");

                    b.ToTable("KindOfAnimals");
                });

            modelBuilder.Entity("Vetotvet.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BreedId");

                    b.Property<string>("Chip");

                    b.Property<int?>("ClientId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<int?>("KindOfAnimalId");

                    b.Property<string>("Name");

                    b.Property<string>("Sex");

                    b.HasKey("Id");

                    b.HasIndex("BreedId");

                    b.HasIndex("ClientId");

                    b.HasIndex("KindOfAnimalId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Vetotvet.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId");

                    b.Property<DateTime>("DateTime");

                    b.Property<int?>("PetId");

                    b.Property<string>("Reason");

                    b.Property<string>("Recommendation");

                    b.Property<float>("Summ");

                    b.Property<string>("Treatment");

                    b.Property<int?>("VisitTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PetId");

                    b.HasIndex("VisitTypeId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Vetotvet.Models.VisitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("VisitType");
                });

            modelBuilder.Entity("Vetotvet.Models.Pet", b =>
                {
                    b.HasOne("Vetotvet.Models.Breed", "Breed")
                        .WithMany()
                        .HasForeignKey("BreedId");

                    b.HasOne("Vetotvet.Models.Client")
                        .WithMany("Pets")
                        .HasForeignKey("ClientId");

                    b.HasOne("Vetotvet.Models.KindOfAnimal", "KindOfAnimal")
                        .WithMany()
                        .HasForeignKey("KindOfAnimalId");
                });

            modelBuilder.Entity("Vetotvet.Models.Visit", b =>
                {
                    b.HasOne("Vetotvet.Models.Client", "Client")
                        .WithMany("Visits")
                        .HasForeignKey("ClientId");

                    b.HasOne("Vetotvet.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId");

                    b.HasOne("Vetotvet.Models.VisitType", "VisitType")
                        .WithMany()
                        .HasForeignKey("VisitTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
